---
# tasks file for emorylib_role_imagemagick_ghostscript_image_libraries

- name: Gather package facts
  package_facts:

- name: Include tasks to install ImageMagick Lib
  include_tasks:
    file: install_imagemagick_lib.yml
    apply:
      vars:
        __imagemagick_lib_installed: '{{ imagemagick_lib_installed }}'
  when: 
    - imagemagick_lib_version != false
    - imagemagick_lib_installed == false or installed != imagemagick_lib_version
  vars:
    imagemagick_lib_installed: '{{ true if ansible_facts.packages["ImageMagick-lib"] is defined else false }}'
    installed_version: '{{ ansible_facts.packages["ImageMagick-lib"][0]["version"] | d() }}'
    installed_release: '{{ ansible_facts.packages["ImageMagick-lib"][0]["release"] | d() }}'
    installed: '{{ installed_version }}-{{ installed_release }}'

- name: Include tasks to install ImageMagick
  include_tasks:
    file: install_imagemagick.yml
    apply:
      vars:
        __imagemagick_installed: '{{ imagemagick_installed }}'
  when: 
    - imagemagick_version != false
    - imagemagick_installed == false or installed != imagemagick_version
  vars:
    imagemagick_installed: '{{ true if ansible_facts.packages["ImageMagick"] is defined else false }}'
    installed_version: '{{ ansible_facts.packages["ImageMagick"][0]["version"] | d() }}'
    installed_release: '{{ ansible_facts.packages["ImageMagick"][0]["release"] | d() }}'
    installed: '{{ installed_version }}-{{ installed_release }}'

- name: Get ghostscript version
  shell: gs --version
  register: gs_version

- name: Check if versions match
  set_fact:
    gs_version_match: '{{ true if gs_version.stdout is version(ghostscript_version, ==) else false }}'

- name: Include tasks to install ghostscript
  include_tasks:
    file: install_ghostscript.yml
  when: not gs_version_match